STSWENG-125: API's for View Product Page
kayecandy/gcakes-be pull request #12
Opened 2023-03-21 13:46 UTC by alankun5

2023-03-22 13:12 UTC, kayecandy requested changes

2023-03-22 13:12 UTC, kayecandy commented on api/products/getReviews.ts
Let's rename this to 

`api/products/reviews.ts`

2023-03-22 13:12 UTC, kayecandy commented on api/products/view/[productId].ts
Rename to

`api/products/[productId]/index.ts`

2023-03-22 13:12 UTC, kayecandy commented on api/reviews/[productId].ts
Rename to

`api/products/[productId]/reviews`

2023-03-24 06:26 UTC, alankun5 commented
@kayecandy changes addressed :)

2023-03-29 11:14 UTC, kayecandy approved these changes

2023-03-29 11:15 UTC, merged